/* Generated By:JavaCC: Do not edit this line. burgercodeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface burgercodeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 6;
  /** RegularExpression Id. */
  int INICIOBLOCO = 7;
  /** RegularExpression Id. */
  int FIMBLOCO = 8;
  /** RegularExpression Id. */
  int REAL = 9;
  /** RegularExpression Id. */
  int INTEIRO = 10;
  /** RegularExpression Id. */
  int LETRA = 11;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 12;
  /** RegularExpression Id. */
  int DIGITO = 13;
  /** RegularExpression Id. */
  int VIRGULA = 14;
  /** RegularExpression Id. */
  int NUMERO = 15;
  /** RegularExpression Id. */
  int CARACTERE = 16;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 17;
  /** RegularExpression Id. */
  int ATRIBUICAO = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int FIMIF = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int PARA = 24;
  /** RegularExpression Id. */
  int PRINT = 25;
  /** RegularExpression Id. */
  int SOMA = 26;
  /** RegularExpression Id. */
  int SUBTRACAO = 27;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 28;
  /** RegularExpression Id. */
  int DIVISAO = 29;
  /** RegularExpression Id. */
  int ABRECHAVE = 30;
  /** RegularExpression Id. */
  int FECHACHAVE = 31;
  /** RegularExpression Id. */
  int ABREPAR = 32;
  /** RegularExpression Id. */
  int FECHAPAR = 33;
  /** RegularExpression Id. */
  int NEGACAO = 34;
  /** RegularExpression Id. */
  int IGUALIGUAL = 35;
  /** RegularExpression Id. */
  int IGUAL = 36;
  /** RegularExpression Id. */
  int IGUALMAIOR = 37;
  /** RegularExpression Id. */
  int MAIOR = 38;
  /** RegularExpression Id. */
  int IGUALMENOR = 39;
  /** RegularExpression Id. */
  int MENOR = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"liga\"",
    "\"prepara\"",
    "\"entrega\"",
    "\"xsalada\"",
    "\"xburger\"",
    "\"xtudo\"",
    "\"prensou\"",
    "<DIGITO>",
    "\",\"",
    "<NUMERO>",
    "<CARACTERE>",
    "<IDENTIFICADOR>",
    "\"adiciona\"",
    "\"tacomfome?\"",
    "\"fimse\"",
    "\"saboreando\"",
    "\"fazer\"",
    "\"enquanto\"",
    "\"ate\"",
    "\"cardapio\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"!=\"",
    "\"==\"",
    "\"=\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
  };

}
