/* Generated By:JavaCC: Do not edit this line. burgercodeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface burgercodeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 5;
  /** RegularExpression Id. */
  int INICIOBLOCO = 6;
  /** RegularExpression Id. */
  int FIMBLOCO = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int INTEIRO = 9;
  /** RegularExpression Id. */
  int LETRA = 10;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 11;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 12;
  /** RegularExpression Id. */
  int DIGITO = 13;
  /** RegularExpression Id. */
  int NUMERO = 14;
  /** RegularExpression Id. */
  int CARACTERE = 15;
  /** RegularExpression Id. */
  int ATRIBUICAO = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int FIMIF = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int PARA = 22;
  /** RegularExpression Id. */
  int PRINT = 23;
  /** RegularExpression Id. */
  int SOMA = 24;
  /** RegularExpression Id. */
  int SUBTRACAO = 25;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 26;
  /** RegularExpression Id. */
  int DIVISAO = 27;
  /** RegularExpression Id. */
  int ABRECHAVE = 28;
  /** RegularExpression Id. */
  int FECHACHAVE = 29;
  /** RegularExpression Id. */
  int ABREPAR = 30;
  /** RegularExpression Id. */
  int FECHAPAR = 31;
  /** RegularExpression Id. */
  int NEGACAO = 32;
  /** RegularExpression Id. */
  int IGUALIGUAL = 33;
  /** RegularExpression Id. */
  int IGUAL = 34;
  /** RegularExpression Id. */
  int MENORIGUAL = 35;
  /** RegularExpression Id. */
  int MAIORIGUAL = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"liga\"",
    "\"prepara\"",
    "\"entrega\"",
    "\"xtudo\"",
    "\"xsalada\"",
    "\"hamburguer\"",
    "\"prensou\"",
    "<IDENTIFICADOR>",
    "<DIGITO>",
    "<NUMERO>",
    "<CARACTERE>",
    "\"adiciona\"",
    "\"se\"",
    "\"fimse\"",
    "\"para\"",
    "\"fazer\"",
    "\"enquanto\"",
    "\"ate\"",
    "\"mostra\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"!=\"",
    "\"==\"",
    "\"=\"",
    "\"<=\"",
    "\">=\"",
  };

}
